name: NDepend-DailyBuildAnalyis-Results
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - name: Run a PowerShell script
        shell: pwsh
        run: D:\NDependDailyBuild.ps1
