name: Send email notification

on:
  push:
    branches: [main]

jobs:
  send_email:
    runs-on: self-hosted
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: 'tushar.burhan@amla.io'
          password: 'Tushar@2509'
          subject: Github Actions job result
          to: tushar.burhan@amla.io,ashish.rasekar@amla.io
          from: Luke Skywalker <user@example.com>
          body: Build job of ${{ github.repository }} completed successfully!
          priority: low
